language: go
notifications:
  email: false
env:
  - ZOOKEEPER_VERSION="3.4.6"
go:
  - 1.3
  - 1.4
  - 1.5
cache:
  directories:
    - $HOME/zookeeper-$ZOOKEEPER_VERSION
install:
  - test -d zookeeper-$ZOOKEEPER_VERSION || (wget -O zookeeper-$ZOOKEEPER_VERSION.tar.gz http://mirrors.rackhosting.com/apache/zookeeper/zookeeper-$ZOOKEEPER_VERSION/zookeeper-$ZOOKEEPER_VERSION.tar.gz && tar -xvf zookeeper-$ZOOKEEPER_VERSION.tar.gz -C $HOME)
script:
  - ZOOKEEPER_PATH="$HOME/zookeeper-$ZOOKEEPER_VERSION" make test
